import streamlit as st
import subprocess
import shutil
import re
from pathlib import Path

# ==================================================
# Streamlit setup
# ==================================================
st.set_page_config(layout="wide")
st.title("Steel System Optimization (AMPL)")
st.caption("Edit parameters → Run AMPL → View results")

# ==================================================
# Paths
# ==================================================
BASE_DIR = Path(__file__).parent
PARAM_FILE = BASE_DIR / "parameters.mod"
USER_PARAM_FILE = BASE_DIR / "user_parameters.mod"
MAIN_MOD_FILE = BASE_DIR / "main.mod"
RUN_FILE = BASE_DIR / "run_ampl.run"

# ==================================================
# Sanity checks
# ==================================================
missing = [f.name for f in [PARAM_FILE, MAIN_MOD_FILE] if not f.exists()]
if missing:
    st.error(f"Missing required files: {', '.join(missing)}")
    st.stop()

AMPL_EXE = shutil.which("ampl")
if not AMPL_EXE:
    st.error("AMPL executable not found in PATH")
    st.stop()

# ==================================================
# Extract scalar DEFAULT parameters
# ==================================================
param_pattern = re.compile(
    r"^\s*param\s+(\w+)\s+default\s+([0-9.eE+-]+)\s*;",
    re.IGNORECASE
)

def load_parameters():
    params = {}
    with open(PARAM_FILE, "r") as f:
        for line in f:
            m = param_pattern.match(line)
            if m:
                params[m.group(1)] = float(m.group(2))
    return params

params = load_parameters()

if not params:
    st.error(
        "No scalar DEFAULT parameters found.\n\n"
        "Make sure parameters are declared as:\n"
        "param x default 10;"
    )
    st.stop()

# ==================================================
# Sidebar: parameter editor
# ==================================================
st.sidebar.header("Model Parameters")

user_params = {}
for k, v in sorted(params.items()):
    user_params[k] = st.sidebar.number_input(
        label=k,
        value=v,
        format="%.6f"
    )

# ==================================================
# Write user_parameters.mod using LET (override)
# ==================================================
def write_user_parameters(p):
    with open(USER_PARAM_FILE, "w") as f:
        f.write("# Auto-generated by Streamlit\n\n")
        for k, v in p.items():
            f.write(f"let {k} := {v};\n")

# ==================================================
# Create run file (NO solve here)
# ==================================================
if not RUN_FILE.exists():
    with open(RUN_FILE, "w") as f:
        f.write(
            "reset;\n"
            "include parameters.mod;\n"
            "include user_parameters.mod;\n"
            "include main.mod;\n"
            "solve;\n\n"
            "include cost_report.mod;\n"
            "include emissions_report.mod;\n"
            "include report.mod;\n"
        )

# ==================================================
# Run AMPL
# ==================================================
if st.button("Run Optimization", type="primary"):

    write_user_parameters(user_params)

    with st.spinner("Running AMPL optimization..."):
        result = subprocess.run(
            [AMPL_EXE, str(RUN_FILE)],
            cwd=BASE_DIR,
            capture_output=True,
            text=True
        )

    if result.returncode != 0:
        st.error("AMPL execution failed")
        st.subheader("STDERR")
        st.text(result.stderr)
    else:
        st.success("Optimization completed")

        st.subheader("AMPL Output")

        output = ""
        if result.stdout and result.stdout.strip():
            output += result.stdout

        if result.stderr and result.stderr.strip():
            output += "\n" + result.stderr

        if not output.strip():
            st.warning("AMPL ran successfully but produced no console output.")
        else:
            st.text(output)

