import streamlit as st
import subprocess
import re
from pathlib import Path
import shutil

# ==================================================
# Streamlit setup
# ==================================================
st.set_page_config(layout="wide")
st.title("Steel System Optimization (AMPL)")
st.caption("Edit parameters → Run AMPL → View results")

# ==================================================
# Paths (repo root)
# ==================================================
BASE_DIR = Path(__file__).parent

PARAM_FILE = BASE_DIR / "parameters.mod"
USER_PARAM_FILE = BASE_DIR / "user_parameters.mod"
MAIN_MOD_FILE = BASE_DIR / "main.mod"
RUN_FILE = BASE_DIR / "run_ampl.run"
RESULTS_FILE = BASE_DIR / "results.txt"

# ==================================================
# Sanity checks
# ==================================================
missing = [f.name for f in [PARAM_FILE, MAIN_MOD_FILE] if not f.exists()]
if missing:
    st.error(f"Missing required files: {', '.join(missing)}")
    st.stop()

# ==================================================
# Detect AMPL executable
# ==================================================
AMPL_EXE = shutil.which("ampl")
if not AMPL_EXE:
    st.error("AMPL executable not found in PATH. Please install AMPL or add it to PATH.")
    st.stop()

# ==================================================
# Extract scalar parameters from parameters.mod
# ==================================================
param_pattern = re.compile(
    r"^\s*param\s+(\w+)\s*:=\s*([0-9.eE+-]+)\s*;",
    re.IGNORECASE
)

def load_parameters():
    params = {}
    with open(PARAM_FILE, "r") as f:
        for line in f:
            match = param_pattern.match(line)
            if match:
                name, value = match.groups()
                params[name] = float(value)
    return params

params = load_parameters()
if not params:
    st.error("No scalar parameters found in parameters.mod")
    st.stop()

# ==================================================
# Sidebar: parameter editor
# ==================================================
st.sidebar.header("Model Parameters")
user_params = {}
for name, value in sorted(params.items()):
    user_params[name] = st.sidebar.number_input(
        label=name,
        value=value,
        format="%.6f"
    )

# ==================================================
# Write user parameter file
# ==================================================
def write_user_parameters(params_dict):
    with open(USER_PARAM_FILE, "w") as f:
        f.write("# ==============================================\n")
        f.write("# Auto-generated by Streamlit (overrides defaults)\n")
        f.write("# ==============================================\n\n")
        for k, v in params_dict.items():
            f.write(f"param {k} := {v};\n")

# ==================================================
# Create run_ampl.run if missing
# ==================================================
if not RUN_FILE.exists():
    with open(RUN_FILE, "w") as f:
        f.write(
            "# Auto-generated run file for Streamlit\n"
            "include parameters.mod;\n"
            "include user_parameters.mod;\n"
            "include main.mod;\n"
        )

# ==================================================
# Run AMPL
# ==================================================
if st.button("Run Optimization", type="primary"):

    write_user_parameters(user_params)

    with st.spinner("Running AMPL optimization..."):
        result = subprocess.run(
            [AMPL_EXE, str(RUN_FILE)],
            cwd=BASE_DIR,
            capture_output=True,
            text=True
        )

    st.subheader("AMPL Output")
    st.text("=== STDOUT ===")
    st.text(result.stdout)
    st.text("=== STDERR ===")
    st.text(result.stderr)

    if result.returncode != 0:
        st.error("AMPL execution failed. Check the STDERR above for details.")
    else:
        st.success("Optimization completed successfully")
        if RESULTS_FILE.exists():
            st.subheader("Results from results.txt")
            st.text(RESULTS_FILE.read_text())
        else:
            st.warning("results.txt not found – check run_ampl.run")
