import streamlit as st
import subprocess
import re
from pathlib import Path

# ==================================================
# Streamlit setup
# ==================================================
st.set_page_config(layout="wide")
st.title("AMPL Steel Model – Parameter Editor")

# ==================================================
# GitHub repo configuration
# ==================================================
REPO_URL = "https://github.com/nakulneupane/Steel-optimization.git"

BASE_DIR = Path(__file__).parent
REPO_DIR = BASE_DIR / "Steel-optimization"

MODEL_DIR = REPO_DIR / "model"
RUNS_DIR = REPO_DIR / "runs"

PARAM_FILE = MODEL_DIR / "parameters.mod"
USER_PARAM_FILE = MODEL_DIR / "user_parameters.mod"
RUN_FILE = RUNS_DIR / "run_ampl.run"

# ==================================================
# Clone repo if not present
# ==================================================
if not REPO_DIR.exists():
    with st.spinner("Cloning AMPL model from GitHub..."):
        try:
            subprocess.run(
                ["git", "clone", REPO_URL],
                cwd=BASE_DIR,
                check=True,
                capture_output=True,
                text=True
            )
            st.success("Repository cloned successfully")
        except subprocess.CalledProcessError as e:
            st.error("Failed to clone GitHub repository")
            st.text(e.stderr)
            st.stop()

# ==================================================
# Extract scalar parameters from parameters.mod
# ==================================================
param_pattern = re.compile(
    r"^\s*param\s+(\w+)\s*:=\s*([0-9.eE+-]+)\s*;",
    re.IGNORECASE
)

def load_parameters():
    params = {}
    try:
        with open(PARAM_FILE, "r") as f:
            for line in f:
                match = param_pattern.match(line)
                if match:
                    name, value = match.groups()
                    params[name] = float(value)
    except FileNotFoundError:
        st.error("parameters.mod not found in repository")
        st.stop()
    return params

params = load_parameters()

if not params:
    st.error("No scalar parameters found in parameters.mod")
    st.stop()

# ==================================================
# Sidebar parameter editor
# ==================================================
st.sidebar.header("Edit Model Parameters")

user_params = {}
for name, value in sorted(params.items()):
    user_params[name] = st.sidebar.number_input(
        label=name,
        value=value,
        format="%.6f"
    )

# ==================================================
# Write overriding parameter file
# ==================================================
def write_user_parameters(params_dict):
    with open(USER_PARAM_FILE, "w") as f:
        f.write("# ==============================================\n")
        f.write("# Auto-generated by Streamlit (DO NOT EDIT)\n")
        f.write("# ==============================================\n\n")
        for k, v in params_dict.items():
            f.write(f"param {k} := {v};\n")

# ==================================================
# Run AMPL
# ==================================================
if st.button("Run Optimization", type="primary"):

    write_user_parameters(user_params)

    with st.spinner("Running AMPL optimization..."):
        result = subprocess.run(
            ["ampl", str(RUN_FILE)],
            cwd=REPO_DIR,
            capture_output=True,
            text=True
        )

    if result.returncode != 0:
        st.error("AMPL execution failed")
        st.subheader("AMPL error output")
        st.text(result.stderr)
    else:
        st.success("Optimization completed successfully")
        st.subheader("AMPL output")
        st.text(result.stdout)

        results_file = REPO_DIR / "results.txt"
        if results_file.exists():
            st.subheader("Results")
            st.text(results_file.read_text())
        else:
            st.warning("results.txt not found (check run_ampl.run)")
